# Install PHP & MySQL for running sites on WordPress
# Run mysql_secure_install playbook to complete installation on first provision

- name: install apt packages for php 
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - php7.0-fpm
    - php7.0-memcached
    - php7.0-mcrypt
    - php7.0-gd
    - imagemagick
    - php7.0-imagick
    - php7.0-curl
    - php7.0-mysql
    - libapache2-mod-php7.0
    - imagemagick

- name: set php.ini for php-fpm
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp=fix_pathinfo=1 line=cgi.fix_pathinfo=0

- name: set post_max_size for uploads
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp="post_max_size" line="post_max_size = 10M"

- name: set max file upload size to 10MB
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp="upload_max_size = 2M" line="upload_max_size = 10M"
