- name: restart nginx
  service: name=nginx state=restarted

- name: restart sshd
  command: service ssh restart

  # https://github.com/ansible/ansible-modules-core/pull/999
  # service: name=ssh state=restarted

- name: reload php-fpm
  service: name=php5-fpm state=reloaded

- name: restart mysql
  service: name=mysql state=restarted
