# All project build tasks go here. These tasks will only be run for the
# specified commit if the commit hasn't been deployed before or if "force"
# is true.

# Modify as-needed!

- name: check for package.json
  stat: path={{clone_path}}/package.json
  register: npm
  tags: npm

- name: install npm modules
  npm: path="{{clone_path}}"
  when: npm.stat.exists
  ignore_errors: yes
  tags: npm

- name: check for bower.json
  stat: path={{clone_path}}/bower.json
  register: bower
  tags: bower

- name: install bower modules
  command: bower install --allow-root
  args:
    chdir: "{{clone_path}}"
  when: bower.stat.exists
  ignore_errors: yes
  tags: bower

- name: check for gulpfile
  stat: path={{clone_path}}/Gulpfile.js
  register: gulpfile
  tags: gulp

- name: run gulp build task
  command: gulp dist
  args:
    chdir: "{{clone_path}}"
  when: gulpfile.stat.exists
  ignore_errors: yes
  tags: gulp

- name: check for gemfile 
  stat: path={{clone_path}}/Gemfile
  register: gemfile
  tags: gems

- name: install gemfile dependencies with bundler
  command: bash -lc "bundle install"
  args:
    chdir: "{{clone_path}}"
  when: gemfile.stat.exists
  ignore_errors: yes
  tags: gems

- name: check if jekyll project
  command: grep 'jekyll' Gemfile
  args:
    chdir: "{{clone_path}}"
  register: jekyll
  changed_when: False
  ignore_errors: yes
  tags: jekyll

- name: build jekyll site into "public" folder
  shell: bash -lc "jekyll build -d public"
  args:
    chdir: "{{clone_path}}"
  when: jekyll.rc == 0 
  tags: jekyll
