# Clone the repo and check out the specified "commit" (defaults to master)
# unless it has already been checked out. Specifying "force" will clone and
# build regardless of prior status. When done, symlink the specified commit
# to make it go live, and remove old clones to free up disk space.

- name: clone git repo into site_path
  git:
    repo={{synced_folder if local else git_repo}}
    dest={{site_path}}
    version={{commit}}
