#!/bin/sh
set -x

server="46.101.12.100"
site_fqdn=""
build_path=""

ssh deploy@$server <<EOF
  cd /var/www/$site_fqdn

  echo "pulling down latest commits..."
  git pull --rebase

  if (( $? )); then
    echo "Failed to pull down latest changes" >&2
	exit 1
  fi

  echo "building project in: /var/www/$site_fqdn/$build_path"

  echo "installing node packages..."
  npm install --production

  echo "installing bower packages..."
  bower install

  echo "running Gulp build script..."
  gulp dist

  exit
EOF

# Other build steps, use as needed
# echo "installing gems from Gemfile..."
# bundle install
# echo "building Jekyll site..."
# jekyll build -d public
