# Add a user account for the currently logged-in user (development), otherwise
# add all users defined in group_vars/all (production).

- include: localuser.yml
  when: env == "development"

- include: users.yml
  when: env != "development"

- name: fetch dotfiles for user
  git:
    repo=git@github.com:{{ item.github_name }}/dotfiles.git
    dest=/home/{{ item.name }}/dotfiles
  when: item.dotfiles is defined
  with_items: users
