# Configure the box. This happens after the base initialization, but before
# the project is cloned or built.

- name: set hostname
  hostname: name={{hostname}}

- name: add loopback references to our domain in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    state=present
    line="127.0.0.1 {{hostname}} {{site_fqdn}}"

- name: disallow password authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
  notify: restart sshd

- name: disallow challenge response authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp="^ChallengeResponseAuthentication"
    line="ChallengeResponseAuthentication no"
  notify: restart sshd

- name: ensure github.com is a known host
  lineinfile:
    dest=/etc/ssh/ssh_known_hosts
    state=present
    create=yes
    regexp="^github\\.com"
    line="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"

- name: ensure ssh agent socket environment variable persists when sudoing
  lineinfile:
    dest=/etc/sudoers
    state=present
    insertafter="^Defaults"
    line='Defaults\tenv_keep += "SSH_AUTH_SOCK"'
    validate="visudo -cf %s"

- name: allow passwordless sudo - development only!
  lineinfile:
    dest=/etc/sudoers
    state=present
    regexp="^%sudo"
    line="%sudo ALL=(ALL:ALL) NOPASSWD:ALL"
    validate="visudo -cf %s"
  when: env == "development"

- name: check swapfile enabled
  command: swapon -s | grep swapfile
  register: swapfile

- name: enable swapfile if not exists
  shell: dd if=/dev/zero of=/swapfile bs=1024 count=256k && mkswap /swapfile && swapon /swapfile
  when: swapfile.stdout.find('swapfile') == -1 # when "swapfile" not found in stdout

- name: check swapfile in fstab
  lineinfile:
    dest=/etc/fstab
    state=present
    regexp="swapfile"
    line="/swapfile       none    swap    sw      0       0"

- name: set swappiness
  shell: echo 10 | sudo tee /proc/sys/vm/swappiness && echo vm.swappiness = 10 | sudo tee -a /etc/sysctl.conf
  when: swapfile.stdout.find('swapfile') == -1 # when "swapfile" not found in stdout

- name: set swapfile permissions
  shell: sudo chown root:root /swapfile && sudo chmod 0600 /swapfile
  when: swapfile.stdout.find('swapfile') == -1 # when "swapfile" not found in stdout
